/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthenticatedWordsRouteImport } from './routes/_authenticated/words'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPracticeQuizRouteImport } from './routes/_authenticated/practice/quiz'
import { Route as AuthenticatedPracticeFlashcardsRouteImport } from './routes/_authenticated/practice/flashcards'
import { Route as AuthenticatedPracticeAiRouteImport } from './routes/_authenticated/practice/ai'
import { Route as AuthenticatedAdminSeedRouteImport } from './routes/_authenticated/admin/seed'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWordsRoute = AuthenticatedWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeQuizRoute =
  AuthenticatedPracticeQuizRouteImport.update({
    id: '/practice/quiz',
    path: '/practice/quiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeFlashcardsRoute =
  AuthenticatedPracticeFlashcardsRouteImport.update({
    id: '/practice/flashcards',
    path: '/practice/flashcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeAiRoute = AuthenticatedPracticeAiRouteImport.update({
  id: '/practice/ai',
  path: '/practice/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSeedRoute = AuthenticatedAdminSeedRouteImport.update({
  id: '/admin/seed',
  path: '/admin/seed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/words': typeof AuthenticatedWordsRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/seed': typeof AuthenticatedAdminSeedRoute
  '/practice/ai': typeof AuthenticatedPracticeAiRoute
  '/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/practice/quiz': typeof AuthenticatedPracticeQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/words': typeof AuthenticatedWordsRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/seed': typeof AuthenticatedAdminSeedRoute
  '/practice/ai': typeof AuthenticatedPracticeAiRoute
  '/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/practice/quiz': typeof AuthenticatedPracticeQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/words': typeof AuthenticatedWordsRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/admin/seed': typeof AuthenticatedAdminSeedRoute
  '/_authenticated/practice/ai': typeof AuthenticatedPracticeAiRoute
  '/_authenticated/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/_authenticated/practice/quiz': typeof AuthenticatedPracticeQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/statistics'
    | '/tags'
    | '/words'
    | '/api/tts'
    | '/admin/seed'
    | '/practice/ai'
    | '/practice/flashcards'
    | '/practice/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/statistics'
    | '/tags'
    | '/words'
    | '/api/tts'
    | '/admin/seed'
    | '/practice/ai'
    | '/practice/flashcards'
    | '/practice/quiz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/tags'
    | '/_authenticated/words'
    | '/api/tts'
    | '/_authenticated/admin/seed'
    | '/_authenticated/practice/ai'
    | '/_authenticated/practice/flashcards'
    | '/_authenticated/practice/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/words': {
      id: '/_authenticated/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof AuthenticatedWordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/quiz': {
      id: '/_authenticated/practice/quiz'
      path: '/practice/quiz'
      fullPath: '/practice/quiz'
      preLoaderRoute: typeof AuthenticatedPracticeQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/flashcards': {
      id: '/_authenticated/practice/flashcards'
      path: '/practice/flashcards'
      fullPath: '/practice/flashcards'
      preLoaderRoute: typeof AuthenticatedPracticeFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/ai': {
      id: '/_authenticated/practice/ai'
      path: '/practice/ai'
      fullPath: '/practice/ai'
      preLoaderRoute: typeof AuthenticatedPracticeAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seed': {
      id: '/_authenticated/admin/seed'
      path: '/admin/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AuthenticatedAdminSeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedWordsRoute: typeof AuthenticatedWordsRoute
  AuthenticatedAdminSeedRoute: typeof AuthenticatedAdminSeedRoute
  AuthenticatedPracticeAiRoute: typeof AuthenticatedPracticeAiRoute
  AuthenticatedPracticeFlashcardsRoute: typeof AuthenticatedPracticeFlashcardsRoute
  AuthenticatedPracticeQuizRoute: typeof AuthenticatedPracticeQuizRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedWordsRoute: AuthenticatedWordsRoute,
  AuthenticatedAdminSeedRoute: AuthenticatedAdminSeedRoute,
  AuthenticatedPracticeAiRoute: AuthenticatedPracticeAiRoute,
  AuthenticatedPracticeFlashcardsRoute: AuthenticatedPracticeFlashcardsRoute,
  AuthenticatedPracticeQuizRoute: AuthenticatedPracticeQuizRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
